spring:
  application:
    name: code3y_idc
  cloud:
    nacos:
      discovery:
        server-addr:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
server:
  port: 8080

buffer:
  executor:
    schedule: true
